# Generated by Django 6.0.5 on 2026-05-31 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('seo_description', models.TextField(verbose_name='SEO описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tasting', models.TextField(blank=True, verbose_name='Дегустация')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Объем, л')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, ₽')),
                ('stock', models.PositiveIntegerField(verbose_name='Наличие на складе, шт.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='В продаже')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goods', to='goods.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goods', to='goods.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
